import "@/styles/global.css";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import Navbar from "@/components/nav";
import { cn } from "@/lib/utils";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="flex-1 flex flex-col">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
